### ISSUE TITLE
Access to methods not-exposed in module interface

### ISSUE THREAD

**Issue by sevenseat** [reasonml-community/bs-jest#16]
Hello!  Is it possible for `bs-jest` to test functions of a module that are not exposed in the module's interface?  I've written a small utility library with a number of private methods that should not be a part of it's public API, so I defined a `rei` file just with the public portions.  But now I can't seem to write unit tests against these private functions.

**Comment by glennsl** [comment]
I have no idea. How would you do it in ES6?

Testing the public API should of course be sufficient, if inconvenient. If you have issues with side-effects, you might want to consider factoring the side-effects out into a separate module, so you can mock it.

**Comment by sevenseat** [comment]
Oops!  My memory was faulty here.  I had thought that Jest had an internal rewire capability that essentially exported everything in a module so that it could be mocked and/or tested.  Nope....  I was hoping bs could replicate non-existent javascript functionality.

Thanks @glennsl .  Closing this issue
