### ISSUE TITLE
Decide on the shape of the expect/assertion API

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-jest#3]
See https://github.com/BuckleTypes/bs-jest/blob/master/__tests__/expect_test.ml for the contestants.

Currently `expect (1 + 2) |> toBe 3` (Expect1) is winning because:
* It's most familiar to existing jest users
* It most closely matches the output of the test runner
* It reads fluently
* It clearly differentiates between expected and actual values
* It's among the most flexible (can even do `expect (1 + 2) = 3` with just 6 or so warnings!)

Runner up: `Assert.(1 + 2 |> toBe 3)`

**Comment by glennsl** [comment]
@chenglou Do you have any strong opinions on this? Otherwise I think I'll go with the above.

**Comment by glennsl** [comment]
I went ahead and settled on my preferred form above for the moment, just to get things moving along. A separate API can also still be implemented alongside.

**Comment by chenglou** [comment]
Yeah sorry for totally paralyzing this. Go ahead!

**Comment by glennsl** [comment]
I think this has been settled purely by the flow time. Can be reconsidered in the future if there's a need though.
